### ISSUE TITLE
PHP Warning during install

### ISSUE THREAD

**Issue by danmarsden** [tigusigalpa/moodle-block_wpfeed#1]
Notice: Undefined variable: postslimitpre in /blocks/wpfeed/block_wpfeed.php on line 389

**Comment by tigusigalpa** [comment]
yes, during travis compliable about long string i make if-else instead short "?" and ":" and i missed that, fix is at github...

**Comment by danmarsden** [comment]
here's another one I saw: 

Notice: Undefined property: block_wpfeed::$staticConfig in /home/dan/www/moodle-r2/blocks/wpfeed/settings.php on line 54

(after hacking it to install with title)

**Comment by tigusigalpa** [comment]
sorry, sorry, sorry.. another missed replace a new var name while travis complable, fixed now

**Comment by danmarsden** [comment]
all good. I can confirm your patch fixed that one.
