### ISSUE TITLE
First time install fails

### ISSUE THREAD

**Issue by danmarsden** [tigusigalpa/moodle-block_wpfeed#2]
Plugin "block_wpfeed" is defective or outdated, can not continue, sorry.

More information about this error

×Debug info: Self test failed.
Error code: detectedbrokenplugin
×Stack trace:
line 845 of /lib/upgradelib.php: plugin_defective_exception thrown
line 429 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
line 1735 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

seems to fail due to block_base::_self_test()
if ($this->get_title() === NULL) {

get_title returns null during fresh install so the block install fails.

looks like you're missing the function init() that most other blocks implement which sets title to a specific var.

**Comment by danmarsden** [comment]
.. but you can probably set it in your _construct() method

**Comment by tigusigalpa** [comment]
yes, init() is not neccessary if class has __construct(), the title defines there. Travis compliable get some troubles)

**Comment by tigusigalpa** [comment]
its ok now at last commit

**Comment by danmarsden** [comment]
yep - installs now.
