### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by danmarsden** [tigusigalpa/moodle-block_wpfeed#3]
Warning: parse_ini_file(../config.ini): failed to open stream: No such file or directory in /home/dan/www/moodle-r2/blocks/wpfeed/db/install.php on line 26

config.ini isn't a typical file used in Moodle plugins - it might be better defining those slightly differently?

**Comment by tigusigalpa** [comment]
hmm, its a good way to make defaults and parse the ones, very strange if its not parsed
also i can make just a static array of defaults, this is a right way you think?

**Comment by tigusigalpa** [comment]
so i need to make PHP-based array of defaults against config.ini?

**Comment by danmarsden** [comment]
I think the error is becuase the install script may be running in a different "path" so "../config.ini" doesn't work - you should be passing the full path using $CFG->dirroot 

but...modifiable config values are usually stored in the config_plugins table, but if it's just to prevent "magic numbers" in code that have no understanding around them many plugins will define constants at the top of their main lib eg:
define('QUIZ_MAX_ATTEMPT_OPTION', 10);

Typically they will be prefixed (we call it frankenstyle) by the plugin type/name eg:
define('BLOCK_WPFEED_SOMEVAR', 10);

occasionally we see these wrapped by "if (defined())" calls so they can be overridden but it's more common for values that can be overridden to be stored in the config_plugins table.

**Comment by tigusigalpa** [comment]
Dan, hi! i start to do this issue, but config.ini stores only default (not modifiable) settings, so the best way is make a static array of these values, but config.ini is the best to work with the ones without class object, just parse_ini_file() function

**Comment by tigusigalpa** [comment]
done
