### ISSUE TITLE
Plugin name when adding block not great

### ISSUE THREAD

**Issue by danmarsden** [tigusigalpa/moodle-block_wpfeed#4]
In the add block dialogue the name of the block is shown as "WPFeed" which isn't great - a better name might be "WordPress Feed" - I'm also not sure why it's pulling this from your config.ini file and not using a lang string? - many sites use multiple languages on the same site - pulling the name from the config file will also prevent the string from being localised based on the users language settings.

**Comment by tigusigalpa** [comment]
Plugin settings allows for user to change the title, but yes, by default it is WPFeed
yes, config.ini has only one such variable that can be set by get_string(), this is a right way, agree

**Comment by tigusigalpa** [comment]
i did that and commited)

**Comment by danmarsden** [comment]
I don't think that's quite right... That string shows in the "add block" dialogue when a teacher/admin wants to add the block to the course. What you're doing there is grabbing it out of the current lang pack and putting it into the settings - which is then used when someone else wants to add the block to a different location, so instead of pulling the name out of "lang" it pulls it out of config with the lang used during install.

But - this follows on with another issue/improvement that you should probably consider (I'll create an issue for that now.)
