### ISSUE TITLE
validation on blog settings page

### ISSUE THREAD

**Issue by danmarsden** [tigusigalpa/moodle-block_wpfeed#6]
It would be nice if you could add some validation to the settings pages that checks to see if the blog url and suffix exist - I had an older WP 4.3 site that I tried initially but it didn't pull any data through because the json stuff wasn't included until 4.4

**Comment by tigusigalpa** [comment]
ok, Dan! will be done at the weekend)

**Comment by tigusigalpa** [comment]
i've added WP REST API v1 support))
